# #4.6 An Alternative Error

## 성공 여부와 에러 메시지를 리턴하는 다른 방법

### 배열로 리턴하기

> UsersService에서 리턴 자료형을 보지 않고서는 리턴 코드가 무얼 의미하는지 알기 힘들다

users.service.ts

```ts
async createAccount({
  email,
  password,
  role,
}: CreateAccountInput): Promise<[boolean, string?]> /* 리턴 자료형 */{
  try {
    const exists = await this.users.findOne({ email });
    if (exists) {
      return [false, '해당 이메일을 가진 사용자가 이미 존재합니다.'];
    }
    await this.users.save(this.users.create({ email, password, role })); // return nothing
    return [true]; // 성공시
  } catch (error) {
    // make error
    return [false, "Couldn't create account"];
  }
}
```

users.resolver.ts

```ts
try {
  const [ok, error] = await this.usersService.createAccount(
    createAccountInput,
  );
  return {
    ok,
    error,
  };
}
```

### 객체로 리턴하기

users.service.ts

```ts
async createAccount({
  email,
  password,
  role,
}: CreateAccountInput): Promise<{ ok: boolean; error?: string }> /* 리턴 자료형 */{
  try {
    const exists = await this.users.findOne({ email });
    if (exists) {
      return {
        ok: false,
        error: '해당 이메일을 가진 사용자가 이미 존재합니다.',
      };
    }
    await this.users.save(this.users.create({ email, password, role }));
    return { ok: true }; // 성공시
  } catch (error) {
    return { ok: false, error: "Couldn't create account" };
  }
}
```

users.resolver.ts

```ts
try {
  const { ok, error } = await this.usersService.createAccount(
    createAccountInput,
  );
  return {
    ok,
    error,
  };
}
```
