# #7.3 Writing Our First Test

## createAccount() - should fail if user exists

- UNIT TESTING은 코드의 최종 출력 값을 테스트하는 것이 아니다.
- 다음 코드는 `user`가 존재할 경우 중간 과정이 제대로 동작하는지 테스트한다.

users.service.spec.ts

```ts
describe('UsersService', () => {
  let service: UsersService;
  let usersRepository: MockRepository;

  beforeAll(async () => {

    ...

  });

  describe('createAccount', () => {
    it('should fail if user exists', async () => {
      // user exists (fake)
      usersRepository.findOne.mockResolvedValue({
        id: 1,
        email: 'alalalalaal',
      });
      const result = await service.createAccount({
        email: '',
        password: '',
        role: 0,
      });
      expect(result).toMatchObject({
        ok: false,
        error: '해당 이메일을 가진 사용자가 이미 존재합니다.',
      });
    });
  });
```

### 설명

- 위 코드는 UsersService의 다음 부분을 UNIT TESTING하게 된다.

  users.service.ts

  ```ts
  async createAccount({
    email,
    password,
    role,
  }: CreateAccountInput): Promise<CreateAccountOutput> {
    try {
      const exists = await this.users.findOne({ email });
      console.log(exists);
      if (exists) {
        return {
          ok: false,
          error: '해당 이메일을 가진 사용자가 이미 존재합니다.',
        };
      }
  ```

- 이처럼 `createAccount()`는 `Repository.save()` 등 외부 요소와 의존 관계를 가진다. 이 모든 의존 관계를 `Mock`으로 대체해야 한다.
- 즉, 가짜로, 존재하는 유저라고 속여야 한다. 어떻게 DB, SQL, TypeORM을 로딩하지 않고 유저가 있는 것처럼 속일까?
  - `Mock` 으로 리턴 값을 속일 수 있다. `createAccount()`와 의존 관계에 있는 것들의 반환 값을 `Mock` 으로 조작한다.
  - 다음 코드는 Jest에게 UsersService의 `findOne()`이 `mockResolvedValue()`의 인자값으로 resolve 할 거라고 알려준다.
    ```ts
    usersRepository.findOne.mockResolvedValue({
      id: 1,
      email: 'alalalalaal',
    });
    ```
  - UsersService 코드에서 `console.log(exists)` 찍어보면 `{ id: 1, email: 'alalalalaal' }`가 출력된다.
- 의도한대로 결과가 리턴되는지 `expect()`와 `toMatch`를 사용한다.
  ```ts
  expect(result).toMatchObject({
    ok: false,
    error: '해당 이메일을 가진 사용자가 이미 존재합니다.',
  });
  ```
